---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

# 12.5: Push your local changes online to GitHub
In pushing the local commit to the git repository, we encountered no issues. We used both the Graphical User Interface and the RStudio command line to try this process and both were successful.

# 12.6: Confirm the local change propagated to the GitHub remote
We both confirmed our changes went through smoothly. Each of us saw our edit appear in the GitHub repository and not interfere with the other's addition.
